FROM golang:1.19-buster AS build

WORKDIR /library_api

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN go build -o main .

EXPOSE 8000

FROM alpine:latest

WORKDIR /root/

RUN apk --no-cache add ca-certificates
COPY --from=0 /library_api ./

CMD ["./main"]