version: "3.8"

networks:
  app:
    driver: bridge

services:
  postgres:
    image: postgres:14-alpine
    container_name: library-api-psql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    command: [ "postgres", "-c", "log_statement=all" ] # log all queries into the container log file
    networks:
      - app
  app:
    build: .
    image: library-api:latest
    container_name: library-api-go
    depends_on:
      - postgres
    ports:
      - "8000:8082"
    restart: on-failure
    environment:
      LISTEN_PORT: 80
      POSTGRES_DB_HOST: postgres
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_NAME: mydatabase
      POSTGRES_DB_USER: myuser
      POSTGRES_DB_PASSWORD: mypassword
    networks:
      - app