FROM golang:1.19-buster AS build

WORKDIR /library_api

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN go build -o /library_api/ ./main.go

EXPOSE 8000

FROM alpine:latest

WORKDIR /library_api

RUN apk --no-cache add ca-certificates
RUN apk add libc6-compat
COPY --from=build /library_api /library_api

CMD ["./main"]